name: lustore
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  google_fonts: 2.1.0
  get_storage: 2.0.3
  jwt_decoder: 2.0.1
  cool_alert: 1.1.0
  bottom_bar_with_sheet: 2.0.1
  intl: 0.17.0
  extended_masked_text: 2.3.1
  image_picker: 0.8.4+3
  flutter_staggered_grid_view: 0.4.1
  brasil_fields: 1.2.0
  get: 4.3.8
  numeric_keyboard: 1.1.0
  syncfusion_flutter_charts: 19.3.47
  infinite_scroll_pagination: 3.1.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/fonts/
    - assets/images/logo.png
    - assets/images/logo-white.png
  uses-material-design: true

get_cli: 
  sub_folder: false

